### ISSUE TITLE
client.devices() returns only first 100 devices

### ISSUE THREAD

**Issue by sn032p** [attm2x/m2x-python#20]
How would the user iterate rest of the devices?

**Comment by kristinpeterson** [comment]
@sn032p this is due to the paginated nature of the List Devices endpoint response, for more details: https://m2x.att.com/developer/documentation/v2/device#List-Devices

Here's a code sample that demonstrates how to iterate over the entire paginated list of Devices using the Python client: 
https://github.com/attm2x/m2x-python/blob/master/examples/iterate_over_devices.py

![screen shot 2016-11-03 at 5 39 12 pm](https://cloud.githubusercontent.com/assets/2113398/19990688/b9ef27b8-a1ec-11e6-9109-7aa1889b2a77.png)
